plugins {
    id 'com.android.library'
}

android {
    namespace 'com.superlauncher'
    compileSdk 36

    defaultConfig {
        minSdk 26
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.preference.ktx
    implementation libs.kotlinx.coroutines.android
}
